### ISSUE TITLE
Slack organization linked in the README is invite only

### ISSUE THREAD

**Issue by stephen-tr** [HubSpot/cms-react#57]
The [link](https://hubspotdev.slack.com/archives/C04AY1H2204) for the slack community in the [welcome section](https://github.com/HubSpot/cms-react/blob/main/README.md#welcome) seems to be invite only, but I see no way of creating an account unless you have an email in the list and there doesn't seem to be a way to request an invite.

Please advise :)

**Comment by happycollision** [comment]
@bran-van-d, is there any way to get an invitation to this?

**Comment by happycollision** [comment]
Ok, for anyone else who also cannot find a way in, I’ve been told that you fill out a form here: https://developers.hubspot.com/slack
